### Signup Store1 User
POST http://localhost:3002/signup
Content-Type: application/json

{
  "Email": "store1@test.com",
  "Name": "Store One",
  "Password": "123456",
  "role": "store1"
}
### Signup Store2 User
POST http://localhost:3002/signup
Content-Type: application/json

{
  "Email": "store2@gmail.com",
  "Name": "Store3",
  "Password": "123456",
  "role": "store2"
}

### Signup Store3 User
POST http://localhost:3002/signup
Content-Type: application/json

{
  "Email": "store3@test.com",
  "Name": "Store3",
  "Password": "123456",
  "role": "store3"
}

### Signup Store4 User
POST http://localhost:3002/signup
Content-Type: application/json

{
  "Email": "store4@test.com",
  "Name": "Store Two",
  "Password": "123456",
  "role": "store4"
}

### Login Store1
POST http://localhost:3002/login
Content-Type: application/json

{
  "LoginEmail": "store2@test.com",
  "LoginPassword": "123456"
}
##forecast prediction
### Login Store1
POST http://localhost:3002/api/predict
Content-Type: application/json

{"store":"WH-1","item":"Book_1","stock":50,"price":100.00}



### Access Store1 Dashboard (Correct Role)
GET http://localhost:3002/store4-dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2LCJlbWFpbCI6InN0b3JlMkB0ZXN0LmNvbSIsInJvbGUiOiJzdG9yZTQiLCJpYXQiOjE3NzU0OTQwOTAsImV4cCI6MTc3NTQ5NzY5MH0.3eUXTpgq1QmxdZGgtUSGE8VPqSKZjiUSfRU9VIhVPVg